name: Deploy Azure Container App

on:
  workflow_call:
    inputs:
      environment:
        description: "The GitHub environment to use"
        required: true
        type: string
      environment_url:
        description: "The URL of the environment"
        required: false
        type: string

      # The sum of the CPU and memory allocation across all containers in the revision must add up to one of the following combinations: 
      # [cpu: 0.25, memory: 0.5Gi]; 
      # [cpu: 0.5, memory: 1.0Gi]; 
      # [cpu: 0.75, memory: 1.5Gi]; 
      # [cpu: 1.0, memory: 2.0Gi]; 
      # [cpu: 1.25, memory: 2.5Gi];
      # [cpu: 1.5, memory: 3.0Gi];
      # [cpu: 1.75, memory: 3.5Gi];
      # [cpu: 2.0, memory: 4.0Gi]

      required_cpu:
        description: "Required CPU in cores from 0.25 - 2.0, e.g. 0.5.  Defaults to 0.25."
        required: false
        type: number
        default: 0.25
      required_memory:
        description: "Required memory from 0.5 - 4.0, e.g. 1.0. Note we do not required the trailing 'Gi' as does the 'az containerapp update' command."
        required: false
        type: number
        default: 0.5
      min_replicas:
        description: "The minimum number of replicas, defaulting to 0."
        required: false
        type: number
        default: 0
      max_replicas:
        description: "The maximum number of replicas, defaulting to 1."
        required: false
        type: number
        default: 1
      docker_image:
        description: "The Docker image to deploy"
        required: true
        type: string
      revision_suffix:
        description: "The revision suffix.  Only set this if you have a real need to set a specific value."
        required: false
        type: string
        default: "${{ github.run_id }}-${{ github.run_attempt }}"
      ingress_target_port:
        description: "The ingress target port."
        required: true
        type: number
      termination_grace_period:
        description: "Duration in seconds a replica is given to gracefully shut down before it is forcefully terminated. Default is 30."
        type: number
        required: false
        default: 30

jobs:
  deploy_to_azure:
    runs-on: ubuntu-latest
    name: Deploy Azure Container App - ${{ vars.NC_APP_COMPONENT_SHORT }} (${{ vars.NC_APP_ENVIRONMENT }})
    environment: 
      name: ${{ inputs.environment }}
      url: ${{inputs.environment_url}}
    permissions:
      id-token: write
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ vars.NC_AZURE_TENANT_ID }}
          client-id: ${{ secrets.NC_AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.NC_AZURE_SUBSCRIPTION_ID_CONTAINER_APP_DEPLOY }}

      - 
        name: Deploy new container
        run: |
          az containerapp update \
            --subscription ${{ secrets.NC_AZURE_SUBSCRIPTION_ID_CONTAINER_APP_DEPLOY }} \
            --resource-group ${{ vars.NC_AZURE_RESOURCE_GROUP_CONTAINER_APP }} \
            --name ${{ vars.NC_AZURE_CONTAINER_APP_NAME }} \
            --cpu ${{ inputs.required_cpu }} \
            --memory "${{ inputs.required_memory }}Gi" \
            --revision-suffix ${{ inputs.revision_suffix }} \
            --min-replicas ${{ inputs.min_replicas }} \
            --max-replicas ${{ inputs.max_replicas }} \
            --termination-grace-period ${{ inputs.termination_grace_period }} \
            --image ${{ inputs.docker_image }}

      - 
        name: Set ingress
        run: |
          az containerapp ingress update \
            --subscription ${{ secrets.NC_AZURE_SUBSCRIPTION_ID_CONTAINER_APP_DEPLOY }} \
            --resource-group ${{ vars.NC_AZURE_RESOURCE_GROUP_CONTAINER_APP }} \
            --name ${{ vars.NC_AZURE_CONTAINER_APP_NAME }} \
            --target-port ${{ inputs.ingress_target_port }}
