# Intended to be called from a push event
name: Push

on:
  workflow_call:
    inputs:
      project_or_solution:
        description: 'The project or solution file to build. If not specified, the action will look for a .sln or .csproj file in the root of the repository.'
        required: false
        type: string
      skip_tests:
        description: 'Skip running tests'
        required: false
        type: boolean
        default: false

jobs:
  parse_semver:
    name: Parse SemVer
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.parse_semver_action.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.parse_semver_action.outputs.dotnet_assembly_version }}
    steps:
      - id: parse_semver_action
        uses: NetChris/parse-semver@fdf7c91e3c241d139205239b3a48d3e0a530f64c
  dotnet-build-test-pack-push-default:
    needs: parse_semver
    permissions:
      checks: write
      contents: read
      packages: write
    uses: ./.github/workflows/dotnet-build-test-pack-push-default.yml
    with:
      # The version here is long but it ensures each push is unique.
      # Additionally, the run ID should be first given lexicographic issues.
      # We want to be able to reference NuGet packages by wildcard so by having this value first we can assume
      # that a subsequent run will always be greater than the previous one.
      # The only corner cases are 1) if GitHub's run ID exceeds the next power of 10 while we're working the same prerelease (highly unlikely)
      # and 2) if we re-attempt the run more than 9 times (also unlikely).
      nuget_version: ${{ needs.parse_semver.outputs.nuget_version }}-${{ github.run_id }}.${{ github.run_attempt }}-${{ github.run_number }}
      dotnet_assembly_version: ${{ needs.parse_semver.outputs.dotnet_assembly_version }}
      project_or_solution: ${{ inputs.project_or_solution }}
      skip_tests: ${{ inputs.skip_tests }}
      # We default to pushing to the organizational feed, so no value for nuget_source
    secrets:
      nuget_api_key: ${{ secrets.GITHUB_TOKEN }}
