# Intended to be called from a push event
name: Push

on:
  workflow_call:

jobs:
  parse_semver:
    name: Parse SemVer
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.parse_semver_action.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.parse_semver_action.outputs.dotnet_assembly_version }}
    steps:
      - id: parse_semver_action
        uses: NetChris/parse-semver@fdf7c91e3c241d139205239b3a48d3e0a530f64c
  dotnet-build-test-pack-push-default:
    needs: parse_semver
    permissions:
      checks: write
      contents: read
      packages: write
    uses: ./.github/workflows/dotnet-build-test-pack-push-default.yml
    with:
      # The version here is long but it ensures each push is unique.
      nuget_version: ${{ needs.parse_semver.outputs.nuget_version }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.run_id }}
      dotnet_assembly_version: ${{ needs.parse_semver.outputs.dotnet_assembly_version }}
      # We default to pushing to the organizational feed, so no value for nuget_source
    secrets:
      nuget_api_key: ${{ secrets.GITHUB_TOKEN }}
