name: Release - GitHub

on:
  workflow_call:
    inputs:
      project_or_solution:
        description: 'The project or solution file to build. If not specified, the action will look for a .sln or .csproj file in the root of the repository.'
        required: false
        type: string
      skip_tests:
        description: 'Skip running tests'
        required: false
        type: boolean
        default: false

jobs:
  enforce_semver:
    name: Enforce SemVer
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.semver_release.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.semver_release.outputs.dotnet_assembly_version }}
    steps:
      - id: semver_release
        uses: NetChris/semver-release@009feae9d273a9944e89abd386adcc3805b85a78
  build-test-pack-push-github:
    name: GitHub NuGet registry
    needs: enforce_semver
    uses: ./.github/workflows/build-test-pack-push-github.yml
    with:
      nuget_version: ${{ needs.enforce_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.enforce_semver.outputs.dotnet_assembly_version }}
      project_or_solution: ${{ inputs.project_or_solution }}
      skip_tests: ${{ inputs.skip_tests }}
    secrets: inherit
